mysql:
  host: 127.0.0.1
  port: 3306
  db: go_chat1
  user: root
  password: 123456789
  log-level: dev
  config: ?charset=utf8mb4&parseTime=True&loc=Local

system:
  host: 0.0.0.0
  port: 8080
  # debug | release | test
  env: debug

logger:
  level: info
  prefix: '[go-chat]'
  director: log
  show-line: true
  log-in-console: true

