info:
  contact: {}
paths:
  /api/user:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名
        in: query
        name: Name
        required: true
        type: string
      - description: 密码
        in: query
        name: Password
        required: true
        type: string
      responses:
        "200":
          description: code", "msg", "data"}
          schema:
            type: string
      summary: 新建用户接口
      tags:
      - 用户
  /api/user/list:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: code", "msg", "data"}
          schema:
            type: string
      summary: 获取所有用户列表
      tags:
      - 用户
swagger: "2.0"
